name: DashLord report

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["DashLord scans"]
    branches: [main]
    types:
      - completed

jobs:
  website:
    runs-on: ubuntu-latest
    name: Website
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/cache@v5
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # build the report
      - id: dashlord-report
        uses: SocialGouv/dashlord-actions/report@v1

      # to save the generated report.json as artifact
      - uses: actions/upload-artifact@v7
        with:
          path: report.json
          name: report
          if-no-files-found: error

      # save full report for history
      - uses: EndBug/add-and-commit@v10
        with:
          add: '["report.json"]'
          author_name: "DashlordBetaGouvBot"
          author_email: "DashlordBetaGouvBot@incubateur.net"
          message: "chore: report update"

      # deploy build to gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3dbacc7e69578703f91f077118b3475862cb09b8
        with:
          branch: gh-pages
          folder: build
